version: 16
port: 5432

defaultdb:
  user: postgres
  password: password

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 50m
    memory: 64Mi

replicaCount: 1

services:
  bonusdb:
    name: bonus_db
    replicaCount: 1
    hostPort: 5432
  flightdb:
    name: flight_db
    replicaCount: 1
    hostPort: 5433
  ticketdb:
    name: ticket_db
    replicaCount: 1
    hostPort: 5434
  authdb:
    name: auth_db
    replicaCount: 1
    hostPort: 5435
  statisticsdb:
    name: statistics_db
    replicaCount: 1
    hostPort: 5436