apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: controller
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: dips.ru
      http:
        paths:
          {{- range $key, $val := .Values.services }}
          {{- if and (hasKey $val "publishUrl") (ne $val.publishUrl "") (ne $val.publishUrl "/") }}
          {{- $path := trimSuffix "/" $val.publishUrl }}
          - path: {{ (printf "%s(/|$)(.*)" $path) | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $val.name }}
                port:
                  number: {{ $val.port }}
          {{- end }}
          {{- end }}
          # Корневой путь для фронтенда – обязательно последним
          {{- range $key, $val := .Values.services }}
          {{- if and (hasKey $val "publishUrl") (eq $val.publishUrl "/") }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $val.name }}
                port:
                  number: {{ $val.port }}
          {{- end }}
          {{- end }}